version: '3'

services:
  cassandra:
    hostname: cassandra
    image: cassandra:latest
    networks:
      - cassandra

  web:
    build: .
    command: /bin/bash -c "cd backend/dzikbook && wait-for-it -t 0 cassandra:9042 -- python manage.py sync_cassandra && python manage.py makemigrations && python manage.py migrate && python manage.py shell && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - cassandra
    networks:
      - cassandra
    environment:
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - CASS_HOST=cassandra

networks:
  cassandra:

